name: Deploy and Release
on:
    push:
        branches: [main]

permissions:
    contents: write

jobs:
    deploy-release:
        name: Deploy and release
        if: github.ref == 'refs/heads/main'
        uses: choctaw-nation/shared-github-actions/.github/workflows/deploy-release.yml@main
        with:
            should_build: true
            plugin_name: # Enter plugin name here
        secrets: inherit
